name: Build and Push Docker Images

on:
  push:
    branches:
      - review-3
  pull_request:
    branches:
      - review-3
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Вход в GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Установка Buildx для Docker
        uses: docker/setup-buildx-action@v3

      - name: Сборка и публикация фронтенда
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/romanov-km/film-react-nest/frontend:latest

      - name: Сборка и публикация бэкенда
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/romanov-km/film-react-nest/backend:latest
